(() => {
  const zh = {
    'ResearcherDNA — Your Research Matters. Make It Tangible.':'ResearcherDNA — 你的科研值得被看见，也值得被留下。',
    'How it works':'如何运作','Example':'示例','For Labs':'实验室方案','Principles':'产品原则','Create yours':'创建你的收藏品',
    'AI identity design for researchers':'为研究者打造的 AI 身份设计','Your Research Matters.':'你的科研值得被看见。','Make It Tangible.':'也值得被留下。',
    'Your research. Your identity. Your collectible.':'你的科研 · 你的身份 · 你的收藏品',
    'Papers, code, projects and milestones already tell your story. ResearcherDNA turns them into a vivid':'论文、代码、项目和里程碑已经构成了你的科研故事。ResearcherDNA 将它们提炼成鲜明的',
    '— then into a collectible made around the researcher you have become.':'，再把它变成一件围绕“你已经成为怎样的研究者”而设计的收藏品。',
    'Create my researcher':'创建我的研究者形象','See an example':'查看示例','Private by default':'默认私密','Every signature object is traceable':'每个标志性物件都可溯源','Try without uploading':'无需上传，先体验',
    'RESEARCH':'科研','MADE PHYSICAL':'实体化','SERIES':'系列','RESEARCHER SERIES · 001':'研究者系列 · 001','AI & ROBOTICS RESEARCHER':'AI 与机器人研究者',
    'Robot':'机器人','Large Language Model':'大语言模型','Digital Twin':'数字孪生','Paper':'论文','FLAGSHIP ARTIFACT':'代表性科研实体','AI × Robotics research system':'AI × 机器人科研系统',
    'FIELD':'领域','Intelligent Systems':'智能系统','FOCUS':'方向','AI · Robotics · Digital Twins':'AI · 机器人 · 数字孪生','NFC':'NFC','Digital profile':'数字科研档案',
    'RESEARCHER FIGURE':'研究者形象','SIGNATURE OBJECTS':'标志性物件','DNA CARD':'DNA 收藏卡','NFC PROFILE':'NFC 数字档案',
    'Research leaves a digital trail.':'科研会留下数字足迹。','We turn those traces into':'我们把这些足迹变成','recognizable research identity':'可被辨识的科研身份','— not just a summary, and not just a figurine.':'——不只是摘要，也不只是一个玩偶。',
    '01 · Understand the work':'01 · 理解科研工作','02 · Select what matters':'02 · 提炼真正重要的元素','03 · Make it collectible':'03 · 变成可收藏的作品',
    'From research to Researcher DNA.':'从科研经历到 Researcher DNA。','Four clear steps, with the researcher in control at every point.':'四个清晰步骤，每一步都由研究者掌控。',
    'CV':'简历','Papers':'论文','Scholar':'Scholar','Share what represents you':'提供能够代表你的资料',
    'Start with your field and role, or add CVs, papers, GitHub, Google Scholar, ResearchGate and other approved sources for a verified result.':'可以只从研究领域和身份开始，也可以添加简历、论文、GitHub、Google Scholar、ResearchGate 等你授权的资料，获得更可靠的结果。',
    'Robotics':'机器人','Multimodal':'多模态','Research':'科研','Vision':'视觉','AI maps your research identity':'AI 刻画你的科研身份',
    'Topics, methods, systems, tools, projects and milestones become a structured Researcher DNA and an interpretable research word cloud.':'研究主题、方法、系统、工具、项目和里程碑会被组织成结构化的 Researcher DNA，并形成可解释的科研词云。',
    'Choose 3–5 signature objects':'选择 3–5 个标志性物件','AI ranks ten candidates. Every candidate shows its evidence trail, and you decide which three to five belong in the final collectible.':'AI 给出 10 个候选物件并展示证据来源，由你决定最终选择其中 3–5 个。',
    'YOUR':'你的','Make it physical':'把科研身份实体化','The approved identity becomes a figure, research objects, flagship artifact, DNA card, packaging and optional NFC profile.':'确认后的科研身份会转化为人物形象、科研物件、代表性科研实体、DNA 收藏卡、包装，以及可选的 NFC 数字档案。',
    'From evidence to a recognizable research identity.':'从真实证据到可被辨识的科研身份。','The system keeps evidence visible, while every interpretation remains editable by the researcher.':'证据始终可见，同时每一项 AI 解读都可以由研究者修改。',
    'APPROVED SOURCES':'已授权资料','Education · projects · skills':'教育 · 项目 · 技能','Selected publications':'代表论文','Methods · systems · contributions':'方法 · 系统 · 贡献','GitHub repositories':'GitHub 仓库','Code · models · experiments':'代码 · 模型 · 实验','Google Scholar':'Google Scholar','Publications · citations · timeline':'论文 · 引用 · 时间线','Projects · publications · profile':'项目 · 论文 · 主页',
    'RESEARCH WORD CLOUD':'科研词云','Large Language Models':'大语言模型','Multimodal AI':'多模态 AI','Representation Learning':'表征学习','Planning':'规划','Foundation Models':'基础模型','Industrial AI':'工业 AI','Simulation':'仿真','extract · connect · rank':'提取 · 关联 · 排序',
    'RESEARCHER DNA':'RESEARCHER DNA','AI & Robotics Researcher':'AI 与机器人研究者','traceable research identity':'可溯源的科研身份','Primary field':'主要领域','Research focus':'研究方向','Robotics · AI · Digital Twins':'机器人 · AI · 数字孪生','Methods':'方法','Transformers · Representation Learning':'Transformer · 表征学习','Signature systems':'代表性系统','Robot · LLM · Digital Twin':'机器人 · 大语言模型 · 数字孪生','Flagship direction':'代表方向','AI-enabled autonomous systems':'AI 驱动的自主智能系统',
    'Traceable signature objects':'可溯源的标志性物件','Every object needs a reason.':'每一个物件都应该有理由。','ResearcherDNA does not pick decorations at random. Each candidate links back to approved evidence such as a paper, repository, project, profile or CV entry. The researcher chooses the final 3–5 objects.':'ResearcherDNA 不会随机选择装饰。每个候选物件都关联到你授权的论文、代码仓库、项目、科研主页或简历证据，最终由研究者亲自选择 3–5 个。',
    'Build my Researcher DNA':'生成我的 Researcher DNA','Robot System':'机器人系统','A concrete visual anchor for work on autonomous, embodied or intelligent systems.':'适合表现自主系统、具身智能和智能系统研究的直观视觉符号。','TRACE → PAPERS · PROJECTS':'溯源 → 论文 · 项目','A recognizable symbol for language, foundation-model or generative-AI research.':'适合表现语言模型、基础模型和生成式 AI 研究的直观符号。','TRACE → PAPERS · GITHUB':'溯源 → 论文 · GitHub','A physical-digital bridge for simulation, intelligent industry and cyber-physical research.':'适合表现仿真、智能工业和信息物理系统研究的虚实桥梁。','TRACE → PROJECTS · CV':'溯源 → 项目 · 简历',
    'Final output':'最终输出','One research identity, five connected artifacts.':'一个科研身份，五种彼此关联的输出。','The physical and digital pieces share the same visual system, story and evidence base — across AI, robotics, biology, medicine, physics, space research and beyond.':'实体与数字内容共享同一套视觉体系、科研故事和证据基础，可覆盖 AI、机器人、生物、医学、物理、航天等不同研究领域。',
    '01 · HERO OBJECT':'01 · 核心实体','Researcher Figure':'研究者形象','A stylized character representing the researcher as a person — not a generic stereotype of their discipline.':'以个性化方式呈现研究者本人，而不是把任何领域都套进统一的“科学家模板”。','02 · SELECTED 3–5':'02 · 选择 3–5 个','Signature Objects':'标志性物件','Three to five traceable symbols selected from ten AI-ranked candidates and confirmed by the researcher.':'从 AI 排序的 10 个候选物件中选择 3–5 个，每个都可溯源并由研究者确认。','03 · FLAGSHIP IDEA':'03 · 代表性科研概念','Research Artifact':'科研实体','A visual object built around a major idea or system — for example a robot, language model, protein structure, telescope or experimental platform.':'围绕重要科研理念或系统制作的实体表达，例如机器人、大语言模型、蛋白质结构、望远镜或实验平台。','04 · IDENTITY SUMMARY':'04 · 身份摘要','Researcher DNA Card':'Researcher DNA 收藏卡','Field, focus, methods, signature objects, milestones and selected work in collectible form.':'以收藏卡形式呈现领域、方向、方法、标志性物件、里程碑和代表成果。','05 · DIGITAL LAYER':'05 · 数字层','NFC Profile':'NFC 数字档案',"A digital research page linked from the physical object, private, unlisted or public by the researcher's choice.":'与实体收藏品连接的数字科研主页，可由研究者选择私密、不公开索引或公开。',
    'FOR LABS · TEAMS · CONFERENCES':'面向实验室 · 团队 · 学术会议','Turn a research group into a collectible universe.':'把一个科研团队变成一套专属收藏系列。','Keep one shared lab identity while giving every member an individual Researcher DNA, traceable signature objects and a research artifact.':'在保留统一实验室视觉身份的同时，让每位成员拥有独立的 Researcher DNA、可溯源物件和科研实体。','PhD graduation':'博士毕业','Postdoc farewell':'博士后离组','Lab anniversary':'实验室纪念日','Keynote gift':'主旨嘉宾礼物','Create a lab member':'创建实验室成员','PROFESSOR':'教授','Robotics · Control':'机器人 · 控制','POSTDOC':'博士后','PHD':'博士生','Computational Science':'计算科学',
    'Built for researchers':'为研究者而设计','AI proposes. The researcher decides.':'AI 提议，研究者决定。','The product is designed around evidence, privacy, purpose limitation and explicit human approval.':'产品围绕证据、隐私、用途限制和明确的人为确认进行设计。','Evidence first':'证据优先','Major identity claims and signature objects can point back to the paper, repository, project or profile that supports them.':'重要身份结论和标志性物件都可以追溯到支持它们的论文、代码仓库、项目或科研主页。','Private & purpose-limited':'默认私密，并限制用途','Uploads remain private by default. Without your explicit permission, we do not publish, disclose, sell or redistribute them, use them for unrelated purposes, or use private uploads to train shared or public AI models.':'上传资料默认保持私密。未经你的明确授权，我们不会公开、披露、出售或传播这些资料，不会将其用于与你所请求的 ResearcherDNA 无关的目的，也不会使用你的私密上传资料训练共享或公开 AI 模型。','You control your data':'资料由你掌控','You decide which sources are used, what appears publicly, and whether a digital profile exists. You can request deletion of uploaded material and generated profiles.':'你决定使用哪些资料、哪些内容可以公开，以及是否创建数字主页；你也可以要求删除上传资料和生成的档案。','Human approval':'人工确认','Nothing goes into a final identity or physical production until the researcher or authorized customer reviews and approves it.':'在研究者或授权客户审核确认之前，任何内容都不会进入最终身份档案或实体制作。',
    'ResearcherDNA privacy commitment':'ResearcherDNA 隐私承诺','We commit not to publish, disclose, sell or distribute your uploaded materials, and not to use them beyond the ResearcherDNA experience you requested — including training shared or public AI models — without your explicit authorization. If you suspect any leak, misuse or unauthorized disclosure, please report it immediately to':'我们承诺：未经你的明确授权，不公开、不披露、不出售、不传播你上传的资料，也不会将其用于你所请求的 ResearcherDNA 体验之外的其他目的，包括训练共享或公开 AI 模型。如发现疑似泄露、滥用或未经授权的传播，请立即举报至',
    'Concept editions':'概念产品','Start digital. Make it physical.':'从数字身份开始，再把它变成实体。','Pricing is intentionally hidden while the product and manufacturing model are being validated.':'产品和制造方案仍在验证阶段，因此当前价格暂以 XX 表示。','DIGITAL':'数字版','Identity profile and digital collectible artwork.':'科研身份档案与数字收藏视觉。','Research word cloud':'科研词云','Collectible artwork':'收藏视觉','Start digital':'创建数字版','CORE PRODUCT':'核心产品','RESEARCHER EDITION':'研究者收藏版','The Collectible':'科研收藏品','The complete researcher figure and traceable signature-object set.':'完整研究者形象与可溯源标志性物件套装。','Researcher figure':'研究者形象','3–5 signature research objects':'3–5 个标志性科研物件','Researcher DNA card':'Researcher DNA 收藏卡','Collector packaging':'收藏包装','Create mine':'创建我的收藏品','ARTIFACT EDITION':'科研实体版','Flagship Edition':'代表成果版','For the research milestone or big idea you want to keep.':'把值得纪念的科研里程碑或重要理念真正留下。','Everything in Researcher Edition':'包含研究者收藏版全部内容','Flagship research artifact':'代表性科研实体','NFC display base':'NFC 展示底座','Numbered collector card':'编号收藏卡','Create flagship':'创建代表成果版','Prototype pricing is not final. Manufacturing, shipping and payment are not connected in this demo.':'当前价格仅为占位，尚未最终确定；本演示尚未连接生产、物流和支付。',
    'Your Research Matters. Make It Tangible.':'你的科研值得被看见，也值得被留下。','Your research took years.':'你的科研投入了很多年。','Give the story a form.':'让这段科研故事拥有实体。','Create your researcher':'创建你的研究者形象','Examples':'示例','Privacy':'隐私','Built by lahoule':'开发者 · lahoule','PRIVACY PROMISE':'隐私承诺','Your uploads stay private: no publication, disclosure, sale, redistribution, unrelated use or shared-model training without your explicit permission.':'你的上传资料保持私密：未经明确授权，不公开、不披露、不出售、不传播、不用于无关用途，也不用于训练共享或公开 AI 模型。','Report concerns · lahoule.lee@gmail.com':'问题举报 · lahoule.lee@gmail.com',
    'Identity':'身份','Preview':'预览','STEP 1 · IDENTITY':'第 1 步 · 身份','Who are we creating?':'我们要为谁创建？','Start with the basics. No uploads are required to explore the first preview.':'先填写基本信息。第一次体验无需上传任何资料。','First name':'名','Last name':'姓','Current role':'当前身份','PhD Researcher':'博士研究生','Postdoctoral Researcher':'博士后研究员','Professor':'教授','Research Scientist':'科研人员','Research Engineer':'科研工程师','Other':'其他','Institution':'机构','Primary research field':'主要研究领域','What is this for?':'这次创建用于什么？','For myself':'为自己创建','Researcher gift':'科研人员礼物','Lab member':'实验室成员','Continue':'继续',
    'STEP 2 · RESEARCH':'第 2 步 · 科研资料','How much should we know?':'你希望我们了解多少？','You can skip this step for a starter Researcher DNA, or add approved sources for a more evidence-grounded result.':'你可以跳过资料上传，先生成基础 Researcher DNA；也可以添加经你授权的资料，获得更有证据支撑的结果。','FAST START':'快速体验','No uploads yet':'暂不上传','Use your role and research field to generate a starter profile.':'根据你的身份和研究领域生成基础档案。','Continue now →':'直接继续 →','OR':'或者','VERIFIED PATH':'可验证路径','Add research sources':'添加科研资料','Use files and links to ground the identity in real work.':'通过文件和链接，让身份建立在真实科研工作之上。','Drop CV or papers here':'将简历或论文拖到这里','PDF, DOCX · Demo only':'PDF、DOCX · 当前为演示','Choose files':'选择文件','ORCID / Personal website':'ORCID / 个人主页','Load lahoule demo sources':'加载 lahoule 演示资料','Useful when you want to test the full verified path.':'用于体验完整的可验证流程。','Your approved sources are used only for the ResearcherDNA experience you request. No publication, sale or redistribution without explicit permission.':'你授权的资料只用于本次 ResearcherDNA 体验。未经明确许可，不公开、不出售、不传播。','Back':'返回','Analyze my research':'分析我的科研',
    'BUILDING YOUR RESEARCHER DNA':'正在生成你的 RESEARCHER DNA','Reading research sources...':'正在读取科研资料…','Extracting topics, methods, systems and recurring ideas.':'正在提取研究主题、方法、系统和反复出现的概念。','STEP 3 · RESEARCHER DNA':'第 3 步 · RESEARCHER DNA','Your research, distilled.':'你的科研，被提炼成身份。','AI proposes a traceable identity and ten candidate objects. You choose the final three to five.':'AI 提出可溯源的科研身份和 10 个候选物件，由你最终选择 3–5 个。','RESEARCH IDENTITY':'科研身份','grounded in provided sources':'基于已提供资料','AI & Robotics':'AI 与机器人','Intelligent Systems · Digital Twins':'智能系统 · 数字孪生','publications':'篇论文','research themes':'个研究主题','methods':'种方法','candidate objects':'个候选物件','What repeatedly appears across your approved sources.':'从你授权的资料中提取反复出现的科研主题。','Derived from CV, papers, GitHub and linked research profiles when provided.':'提供资料时，词云会综合简历、论文、GitHub 和已连接的科研主页生成。','10 TRACEABLE CANDIDATES':'10 个可溯源候选物件','Select 3–5 signature objects.':'选择 3–5 个标志性物件。','Each object shows why it was proposed and where that signal came from.':'每个候选物件都会说明为什么被推荐，以及它来自哪些证据。','selected':'已选择','Choose 3–5':'选择 3–5 个','Continue to design':'继续设计',
    'STEP 4 · PREVIEW':'第 4 步 · 预览','Meet your researcher.':'看看你的研究者收藏品。','A concept preview based on your Researcher DNA. The final product would receive explicit design approval before production.':'这是根据 Researcher DNA 生成的概念预览；真正生产前还需要你明确确认最终设计。','Research system + visual concept':'科研系统 + 可视化概念','Tap to explore ↗':'轻触探索 ↗',"WHAT'S INCLUDED":'包含内容','Researcher Edition':'研究者收藏版','prototype':'原型','signature research objects':'个标志性科研物件','Digital research profile':'数字科研档案','You approve before production':'生产前由你确认','Nothing would be manufactured until the final design and identity are approved.':'只有在最终设计和身份信息得到确认后，才会进入实体制作。','Continue to order':'继续下单','Edit Researcher DNA':'修改 Researcher DNA','PROTOTYPE COMPLETE':'原型流程完成','Your concept is ready.':'你的概念方案已经准备好。','This prototype stops before real payment and manufacturing. The next product layer will connect secure storage, real AI analysis, image/3D generation, ordering and fulfillment.':'当前原型在真实付款和生产前结束。下一阶段将接入安全存储、真实 AI 分析、图像/3D 生成、订单和履约。','Research identity':'科研身份','Edition':'版本','Researcher Edition · XX':'研究者收藏版 · XX','Create another':'再创建一个','Back to website':'返回网站',
    'Your university or lab':'你的大学或实验室','e.g. AI & Robotics':'例如：AI 与机器人',
    'Using your research identity...':'正在使用你的科研身份…','Creating a starter profile from role and field.':'根据身份和研究领域创建基础档案。','Building a research word cloud...':'正在生成科研词云…','Finding recurring themes and research concepts.':'正在识别反复出现的研究主题和概念。','Connecting signals across papers, code and profiles.':'正在关联论文、代码和科研主页中的信号。','Connecting methods and systems...':'正在连接方法与科研系统…','Linking methods to projects and research systems.':'正在将研究方法关联到项目和科研系统。','Ranking traceable objects...':'正在排序可溯源候选物件…','Preparing ten candidates by relevance and visual meaning.':'正在根据相关性和视觉表达价值生成 10 个候选物件。','Preparing ten candidates with evidence trails.':'正在生成带证据链的 10 个候选物件。','Building your Researcher DNA...':'正在生成你的 Researcher DNA…','Preparing a profile you can review and edit.':'正在准备可由你审核和修改的身份档案。',
    'Please select 3–5 signature objects.':'请选择 3–5 个标志性物件。','You can select up to 5 objects.':'最多可以选择 5 个物件。','Select at least 3':'至少选择 3 个','View trace':'查看溯源','Traceable evidence':'证据可溯源',
    'AI Systems Researcher':'AI 系统研究者','Life Science Researcher':'生命科学研究者','Researcher':'研究者','Foundation Models · Multimodal AI · Intelligent Systems':'基础模型 · 多模态 AI · 智能系统','Transformers · Representation Learning · Deep Learning':'Transformer · 表征学习 · 深度学习','Large Language Model · AI Agent · Compute':'大语言模型 · AI Agent · 计算','Foundation-model research system':'基础模型科研系统','Robotics · Intelligent Systems · Digital Twins':'机器人 · 智能系统 · 数字孪生','Transformers · Representation Learning · Control':'Transformer · 表征学习 · 控制','Robot · Large Language Model · Digital Twin':'机器人 · 大语言模型 · 数字孪生','Molecular Systems · Computational Biology':'分子系统 · 计算生物学','Experimental Analysis · Modeling · Machine Learning':'实验分析 · 建模 · 机器学习','Protein · DNA · Imaging System':'蛋白质 · DNA · 成像系统','Computational life-science system':'计算生命科学系统','Research Questions · Systems · Contributions':'科研问题 · 系统 · 贡献','Analysis · Experimentation · Modeling':'分析 · 实验 · 建模','Research Instrument · Data · Model':'科研仪器 · 数据 · 模型','Research project':'科研项目',
    'Robot Arm':'机械臂','Vision System':'视觉系统','Sensor Network':'传感器网络','GPU':'GPU','Dataset':'数据集','Research Paper':'科研论文','Neural Network':'神经网络','Simulation World':'仿真世界','Protein Structure':'蛋白质结构','Microscope':'显微镜','Cell Model':'细胞模型','Genome':'基因组','Imaging System':'成像系统','AI Agent':'AI Agent','GitHub Repository':'GitHub 仓库','Controller':'控制器','Research Instrument':'科研仪器','Experiment':'实验','Lab Notebook':'实验记录','Telescope':'望远镜','Satellite':'卫星',
    'Verified · papers + projects':'已验证 · 论文 + 项目','Verified · papers + GitHub':'已验证 · 论文 + GitHub','Verified · projects + CV':'已验证 · 项目 + 简历','Inferred · papers + code':'推断 · 论文 + 代码','Verified · project evidence':'已验证 · 项目证据','Inferred · GitHub workflow':'推断 · GitHub 工作流','Verified · papers + repositories':'已验证 · 论文 + 仓库','Verified · publication record':'已验证 · 论文记录','Inferred · methods across sources':'推断 · 多资料中的方法','Verified · projects + code':'已验证 · 项目 + 代码','Verified · papers + figures':'已验证 · 论文 + 图示','Verified · research topics':'已验证 · 研究主题','Verified · methods + projects':'已验证 · 方法 + 项目','Verified · papers':'已验证 · 论文','Verified · publication evidence':'已验证 · 论文证据','Verified · methods':'已验证 · 方法','Verified · data sources':'已验证 · 数据来源','Inferred · computational methods':'推断 · 计算方法','Inferred · research workflow':'推断 · 科研工作流','Verified · papers + code':'已验证 · 论文 + 代码','Verified · methods across sources':'已验证 · 多资料中的方法','Verified · projects + code':'已验证 · 项目 + 代码','Verified · repository evidence':'已验证 · 仓库证据','Inferred · multimodal research':'推断 · 多模态研究','Inferred · linked projects':'推断 · 关联项目','Inferred · embodied-AI direction':'推断 · 具身智能方向','Verified · research sources':'已验证 · 科研资料','Inferred · modeling evidence':'推断 · 建模证据','Inferred · project evidence':'推断 · 项目证据','Inferred · system-level theme':'推断 · 系统级主题'
  };

  const fr = {
    'ResearcherDNA — Your Research Matters. Make It Tangible.':'ResearcherDNA — Votre recherche compte. Donnez-lui une forme.',
    'How it works':'Fonctionnement','Example':'Exemple','For Labs':'Pour les labos','Principles':'Principes','Create yours':'Créer le vôtre',
    'AI identity design for researchers':'Identité IA conçue pour les chercheurs','Your Research Matters.':'Votre recherche compte.','Make It Tangible.':'Donnez-lui une forme.','Your research. Your identity. Your collectible.':'Votre recherche. Votre identité. Votre objet de collection.',
    'Papers, code, projects and milestones already tell your story. ResearcherDNA turns them into a vivid':'Articles, code, projets et étapes clés racontent déjà votre parcours. ResearcherDNA les transforme en un',
    '— then into a collectible made around the researcher you have become.':'puis en un objet de collection conçu autour du chercheur que vous êtes devenu.',
    'Create my researcher':'Créer mon chercheur','See an example':'Voir un exemple','Private by default':'Privé par défaut','Every signature object is traceable':'Chaque objet signature est traçable','Try without uploading':'Essayer sans importer de fichier',
    'RESEARCH':'RECHERCHE','MADE PHYSICAL':'RENDUE TANGIBLE','SERIES':'SÉRIE','RESEARCHER SERIES · 001':'SÉRIE CHERCHEUR · 001','AI & ROBOTICS RESEARCHER':'CHERCHEUR IA & ROBOTIQUE','Robot':'Robot','Large Language Model':'Grand modèle de langage','Digital Twin':'Jumeau numérique','Paper':'Article','FLAGSHIP ARTIFACT':'ARTEFACT PHARE','AI × Robotics research system':'Système de recherche IA × robotique','FIELD':'DOMAINE','Intelligent Systems':'Systèmes intelligents','FOCUS':'AXES','AI · Robotics · Digital Twins':'IA · Robotique · Jumeaux numériques','Digital profile':'Profil numérique',
    'RESEARCHER FIGURE':'FIGURINE DU CHERCHEUR','SIGNATURE OBJECTS':'OBJETS SIGNATURE','DNA CARD':'CARTE DNA','NFC PROFILE':'PROFIL NFC','Research leaves a digital trail.':'La recherche laisse une trace numérique.','We turn those traces into':'Nous transformons ces traces en','recognizable research identity':'une identité de recherche reconnaissable','— not just a summary, and not just a figurine.':'— pas seulement un résumé, ni simplement une figurine.','01 · Understand the work':'01 · Comprendre le travail','02 · Select what matters':'02 · Retenir ce qui compte','03 · Make it collectible':'03 · Le rendre collectionnable',
    'From research to Researcher DNA.':'De la recherche au Researcher DNA.','Four clear steps, with the researcher in control at every point.':'Quatre étapes claires, avec le chercheur aux commandes à chaque instant.','Papers':'Articles','Scholar':'Scholar','Share what represents you':'Partagez ce qui vous représente','Start with your field and role, or add CVs, papers, GitHub, Google Scholar, ResearchGate and other approved sources for a verified result.':'Commencez par votre domaine et votre fonction, ou ajoutez CV, articles, GitHub, Google Scholar, ResearchGate et d’autres sources autorisées pour un résultat mieux étayé.','Robotics':'Robotique','Multimodal':'Multimodal','Research':'Recherche','Vision':'Vision','AI maps your research identity':'L’IA cartographie votre identité scientifique','Topics, methods, systems, tools, projects and milestones become a structured Researcher DNA and an interpretable research word cloud.':'Thèmes, méthodes, systèmes, outils, projets et étapes clés deviennent un Researcher DNA structuré et un nuage de mots interprétable.','Choose 3–5 signature objects':'Choisissez 3 à 5 objets signature','AI ranks ten candidates. Every candidate shows its evidence trail, and you decide which three to five belong in the final collectible.':'L’IA classe dix candidats, chacun avec sa trace de preuve, puis vous choisissez les trois à cinq objets finaux.','Make it physical':'Donnez-lui une forme physique','The approved identity becomes a figure, research objects, flagship artifact, DNA card, packaging and optional NFC profile.':'L’identité validée devient une figurine, des objets de recherche, un artefact phare, une carte DNA, un packaging et, si souhaité, un profil NFC.',
    'From evidence to a recognizable research identity.':'Des preuves à une identité scientifique reconnaissable.','The system keeps evidence visible, while every interpretation remains editable by the researcher.':'Les preuves restent visibles et chaque interprétation peut être modifiée par le chercheur.','APPROVED SOURCES':'SOURCES AUTORISÉES','Education · projects · skills':'Formation · projets · compétences','Selected publications':'Publications sélectionnées','Methods · systems · contributions':'Méthodes · systèmes · contributions','GitHub repositories':'Dépôts GitHub','Code · models · experiments':'Code · modèles · expériences','Publications · citations · timeline':'Publications · citations · chronologie','Projects · publications · profile':'Projets · publications · profil','RESEARCH WORD CLOUD':'NUAGE DE MOTS DE RECHERCHE','Large Language Models':'Grands modèles de langage','Multimodal AI':'IA multimodale','Representation Learning':'Apprentissage de représentations','Planning':'Planification','Foundation Models':'Modèles fondamentaux','Industrial AI':'IA industrielle','Simulation':'Simulation','extract · connect · rank':'extraire · relier · classer',
    'AI & Robotics Researcher':'Chercheur IA & robotique','traceable research identity':'identité scientifique traçable','Primary field':'Domaine principal','Research focus':'Axes de recherche','Robotics · AI · Digital Twins':'Robotique · IA · Jumeaux numériques','Methods':'Méthodes','Transformers · Representation Learning':'Transformers · Apprentissage de représentations','Signature systems':'Systèmes signature','Robot · LLM · Digital Twin':'Robot · LLM · Jumeau numérique','Flagship direction':'Direction phare','AI-enabled autonomous systems':'Systèmes autonomes enrichis par l’IA',
    'Traceable signature objects':'Objets signature traçables','Every object needs a reason.':'Chaque objet doit avoir une raison d’être.','ResearcherDNA does not pick decorations at random. Each candidate links back to approved evidence such as a paper, repository, project, profile or CV entry. The researcher chooses the final 3–5 objects.':'ResearcherDNA ne choisit pas des décorations au hasard. Chaque candidat renvoie à des preuves autorisées — article, dépôt, projet, profil ou CV — et le chercheur choisit les 3 à 5 objets finaux.','Build my Researcher DNA':'Créer mon Researcher DNA','Robot System':'Système robotique','A concrete visual anchor for work on autonomous, embodied or intelligent systems.':'Un ancrage visuel concret pour les travaux sur les systèmes autonomes, incarnés ou intelligents.','TRACE → PAPERS · PROJECTS':'TRACE → ARTICLES · PROJETS','A recognizable symbol for language, foundation-model or generative-AI research.':'Un symbole immédiatement reconnaissable pour la recherche en langage, modèles fondamentaux ou IA générative.','TRACE → PAPERS · GITHUB':'TRACE → ARTICLES · GITHUB','A physical-digital bridge for simulation, intelligent industry and cyber-physical research.':'Un pont physique-numérique pour la simulation, l’industrie intelligente et les systèmes cyber-physiques.','TRACE → PROJECTS · CV':'TRACE → PROJETS · CV',
    'Final output':'Résultat final','One research identity, five connected artifacts.':'Une identité scientifique, cinq artefacts reliés.','The physical and digital pieces share the same visual system, story and evidence base — across AI, robotics, biology, medicine, physics, space research and beyond.':'Les éléments physiques et numériques partagent le même langage visuel, la même histoire et la même base de preuves — en IA, robotique, biologie, médecine, physique, spatial et au-delà.','01 · HERO OBJECT':'01 · OBJET CENTRAL','Researcher Figure':'Figurine du chercheur','A stylized character representing the researcher as a person — not a generic stereotype of their discipline.':'Un personnage stylisé représentant le chercheur lui-même, sans le réduire à un stéréotype générique de sa discipline.','02 · SELECTED 3–5':'02 · 3 À 5 SÉLECTIONNÉS','Signature Objects':'Objets signature','Three to five traceable symbols selected from ten AI-ranked candidates and confirmed by the researcher.':'Trois à cinq symboles traçables choisis parmi dix candidats classés par l’IA et confirmés par le chercheur.','03 · FLAGSHIP IDEA':'03 · IDÉE PHARE','Research Artifact':'Artefact de recherche','A visual object built around a major idea or system — for example a robot, language model, protein structure, telescope or experimental platform.':'Un objet visuel construit autour d’une idée ou d’un système majeur — robot, modèle de langage, structure protéique, télescope ou plateforme expérimentale.','04 · IDENTITY SUMMARY':'04 · SYNTHÈSE D’IDENTITÉ','Researcher DNA Card':'Carte Researcher DNA','Field, focus, methods, signature objects, milestones and selected work in collectible form.':'Domaine, axes, méthodes, objets signature, étapes clés et travaux choisis sous forme de carte de collection.','05 · DIGITAL LAYER':'05 · COUCHE NUMÉRIQUE','NFC Profile':'Profil NFC',"A digital research page linked from the physical object, private, unlisted or public by the researcher's choice.":'Une page de recherche numérique liée à l’objet physique, privée, non référencée ou publique selon le choix du chercheur.',
    'FOR LABS · TEAMS · CONFERENCES':'POUR LABOS · ÉQUIPES · CONFÉRENCES','Turn a research group into a collectible universe.':'Transformez une équipe de recherche en univers de collection.','Keep one shared lab identity while giving every member an individual Researcher DNA, traceable signature objects and a research artifact.':'Conservez une identité commune de laboratoire tout en donnant à chaque membre son propre Researcher DNA, des objets signature traçables et un artefact de recherche.','PhD graduation':'Soutenance / diplôme de doctorat','Postdoc farewell':'Départ d’un postdoc','Lab anniversary':'Anniversaire du labo','Keynote gift':'Cadeau pour keynote','Create a lab member':'Créer un membre du labo','PROFESSOR':'PROFESSEUR','Robotics · Control':'Robotique · Contrôle','POSTDOC':'POSTDOC','PHD':'DOCTORANT','Computational Science':'Science computationnelle',
    'Built for researchers':'Conçu pour les chercheurs','AI proposes. The researcher decides.':'L’IA propose. Le chercheur décide.','The product is designed around evidence, privacy, purpose limitation and explicit human approval.':'Le produit est conçu autour de la preuve, de la confidentialité, de la limitation des usages et d’une validation humaine explicite.','Evidence first':'Les preuves d’abord','Major identity claims and signature objects can point back to the paper, repository, project or profile that supports them.':'Les éléments majeurs de l’identité et les objets signature peuvent renvoyer vers l’article, le dépôt, le projet ou le profil qui les justifie.','Private & purpose-limited':'Privé et limité à la finalité','Uploads remain private by default. Without your explicit permission, we do not publish, disclose, sell or redistribute them, use them for unrelated purposes, or use private uploads to train shared or public AI models.':'Les fichiers restent privés par défaut. Sans votre autorisation explicite, nous ne les publions, divulguons, vendons ni redistribuons, ne les utilisons pas à d’autres fins et n’utilisons pas vos fichiers privés pour entraîner des modèles IA partagés ou publics.','You control your data':'Vous contrôlez vos données','You decide which sources are used, what appears publicly, and whether a digital profile exists. You can request deletion of uploaded material and generated profiles.':'Vous décidez quelles sources sont utilisées, ce qui peut être public et si un profil numérique existe. Vous pouvez demander la suppression des fichiers et profils générés.','Human approval':'Validation humaine','Nothing goes into a final identity or physical production until the researcher or authorized customer reviews and approves it.':'Rien n’entre dans l’identité finale ou en production physique avant validation par le chercheur ou le client autorisé.','ResearcherDNA privacy commitment':'Engagement de confidentialité ResearcherDNA','We commit not to publish, disclose, sell or distribute your uploaded materials, and not to use them beyond the ResearcherDNA experience you requested — including training shared or public AI models — without your explicit authorization. If you suspect any leak, misuse or unauthorized disclosure, please report it immediately to':'Nous nous engageons à ne pas publier, divulguer, vendre ou distribuer vos contenus, ni à les utiliser au-delà de l’expérience ResearcherDNA demandée — y compris pour entraîner des modèles IA partagés ou publics — sans votre autorisation explicite. En cas de fuite, d’usage abusif ou de divulgation non autorisée, signalez-le immédiatement à',
    'Concept editions':'Éditions concept','Start digital. Make it physical.':'Commencez en numérique. Rendez-le tangible.','Pricing is intentionally hidden while the product and manufacturing model are being validated.':'Les prix restent volontairement masqués pendant la validation du produit et du modèle de fabrication.','DIGITAL':'NUMÉRIQUE','Identity profile and digital collectible artwork.':'Profil d’identité et visuel de collection numérique.','Research word cloud':'Nuage de mots de recherche','Collectible artwork':'Visuel de collection','Start digital':'Commencer en numérique','CORE PRODUCT':'PRODUIT CENTRAL','RESEARCHER EDITION':'ÉDITION CHERCHEUR','The Collectible':'L’objet de collection','The complete researcher figure and traceable signature-object set.':'La figurine complète et son ensemble d’objets signature traçables.','Researcher figure':'Figurine du chercheur','3–5 signature research objects':'3 à 5 objets signature','Researcher DNA card':'Carte Researcher DNA','Collector packaging':'Packaging de collection','Create mine':'Créer le mien','ARTIFACT EDITION':'ÉDITION ARTEFACT','Flagship Edition':'Édition phare','For the research milestone or big idea you want to keep.':'Pour l’étape clé ou la grande idée de recherche que vous souhaitez conserver.','Everything in Researcher Edition':'Tout le contenu de l’Édition Chercheur','Flagship research artifact':'Artefact de recherche phare','NFC display base':'Socle NFC','Numbered collector card':'Carte de collection numérotée','Create flagship':'Créer l’édition phare','Prototype pricing is not final. Manufacturing, shipping and payment are not connected in this demo.':'Les prix du prototype ne sont pas définitifs. Fabrication, livraison et paiement ne sont pas connectés dans cette démo.',
    'Your Research Matters. Make It Tangible.':'Votre recherche compte. Donnez-lui une forme.','Your research took years.':'Votre recherche a demandé des années.','Give the story a form.':'Donnez une forme à cette histoire.','Create your researcher':'Créer votre chercheur','Examples':'Exemples','Privacy':'Confidentialité','Built by lahoule':'Développé par lahoule','PRIVACY PROMISE':'ENGAGEMENT DE CONFIDENTIALITÉ','Your uploads stay private: no publication, disclosure, sale, redistribution, unrelated use or shared-model training without your explicit permission.':'Vos fichiers restent privés : aucune publication, divulgation, vente, redistribution, utilisation sans rapport ni entraînement de modèles IA partagés sans votre autorisation explicite.','Report concerns · lahoule.lee@gmail.com':'Signaler un problème · lahoule.lee@gmail.com',
    'Identity':'Identité','Preview':'Aperçu','STEP 1 · IDENTITY':'ÉTAPE 1 · IDENTITÉ','Who are we creating?':'Pour qui créons-nous ?','Start with the basics. No uploads are required to explore the first preview.':'Commencez par l’essentiel. Aucun fichier n’est nécessaire pour découvrir le premier aperçu.','First name':'Prénom','Last name':'Nom','Current role':'Fonction actuelle','PhD Researcher':'Doctorant','Postdoctoral Researcher':'Chercheur postdoctoral','Professor':'Professeur','Research Scientist':'Chercheur','Research Engineer':'Ingénieur de recherche','Other':'Autre','Institution':'Établissement','Primary research field':'Domaine principal','What is this for?':'À quelle occasion ?','For myself':'Pour moi','Researcher gift':'Cadeau pour chercheur','Lab member':'Membre du labo','Continue':'Continuer',
    'STEP 2 · RESEARCH':'ÉTAPE 2 · RECHERCHE','How much should we know?':'Que souhaitez-vous nous partager ?','You can skip this step for a starter Researcher DNA, or add approved sources for a more evidence-grounded result.':'Vous pouvez ignorer cette étape pour un Researcher DNA initial, ou ajouter des sources autorisées pour un résultat mieux étayé.','FAST START':'DÉMARRAGE RAPIDE','No uploads yet':'Sans fichier pour l’instant','Use your role and research field to generate a starter profile.':'Utilisez votre fonction et votre domaine pour générer un profil initial.','Continue now →':'Continuer →','OR':'OU','VERIFIED PATH':'PARCOURS VÉRIFIÉ','Add research sources':'Ajouter des sources de recherche','Use files and links to ground the identity in real work.':'Utilisez fichiers et liens pour ancrer l’identité dans vos travaux réels.','Drop CV or papers here':'Déposez CV ou articles ici','PDF, DOCX · Demo only':'PDF, DOCX · Démo','Choose files':'Choisir des fichiers','ORCID / Personal website':'ORCID / Site personnel','Load lahoule demo sources':'Charger les sources démo de lahoule','Useful when you want to test the full verified path.':'Utile pour tester le parcours vérifié complet.','Your approved sources are used only for the ResearcherDNA experience you request. No publication, sale or redistribution without explicit permission.':'Vos sources autorisées sont utilisées uniquement pour l’expérience ResearcherDNA demandée. Aucune publication, vente ou redistribution sans autorisation explicite.','Back':'Retour','Analyze my research':'Analyser ma recherche',
    'BUILDING YOUR RESEARCHER DNA':'CRÉATION DE VOTRE RESEARCHER DNA','Reading research sources...':'Lecture des sources de recherche…','Extracting topics, methods, systems and recurring ideas.':'Extraction des thèmes, méthodes, systèmes et idées récurrentes.','STEP 3 · RESEARCHER DNA':'ÉTAPE 3 · RESEARCHER DNA','Your research, distilled.':'Votre recherche, condensée.','AI proposes a traceable identity and ten candidate objects. You choose the final three to five.':'L’IA propose une identité traçable et dix objets candidats. Vous choisissez les trois à cinq objets finaux.','RESEARCH IDENTITY':'IDENTITÉ DE RECHERCHE','grounded in provided sources':'fondé sur les sources fournies','AI & Robotics':'IA & Robotique','Intelligent Systems · Digital Twins':'Systèmes intelligents · Jumeaux numériques','publications':'publications','research themes':'thèmes de recherche','methods':'méthodes','candidate objects':'objets candidats','What repeatedly appears across your approved sources.':'Ce qui revient le plus souvent dans vos sources autorisées.','Derived from CV, papers, GitHub and linked research profiles when provided.':'Généré à partir du CV, des articles, de GitHub et des profils de recherche reliés lorsqu’ils sont fournis.','10 TRACEABLE CANDIDATES':'10 CANDIDATS TRAÇABLES','Select 3–5 signature objects.':'Sélectionnez 3 à 5 objets signature.','Each object shows why it was proposed and where that signal came from.':'Chaque objet explique pourquoi il a été proposé et d’où vient le signal.','selected':'sélectionnés','Choose 3–5':'Choisissez 3–5','Continue to design':'Continuer vers le design',
    'STEP 4 · PREVIEW':'ÉTAPE 4 · APERÇU','Meet your researcher.':'Découvrez votre chercheur.','A concept preview based on your Researcher DNA. The final product would receive explicit design approval before production.':'Un aperçu conceptuel basé sur votre Researcher DNA. Le produit final nécessiterait une validation explicite avant fabrication.','Research system + visual concept':'Système de recherche + concept visuel','Tap to explore ↗':'Touchez pour explorer ↗',"WHAT'S INCLUDED":'CONTENU','Researcher Edition':'Édition Chercheur','prototype':'prototype','signature research objects':'objets signature','Digital research profile':'Profil de recherche numérique','You approve before production':'Vous validez avant fabrication','Nothing would be manufactured until the final design and identity are approved.':'Rien ne serait fabriqué avant validation du design final et de l’identité.','Continue to order':'Continuer vers la commande','Edit Researcher DNA':'Modifier Researcher DNA','PROTOTYPE COMPLETE':'PROTOTYPE TERMINÉ','Your concept is ready.':'Votre concept est prêt.','This prototype stops before real payment and manufacturing. The next product layer will connect secure storage, real AI analysis, image/3D generation, ordering and fulfillment.':'Ce prototype s’arrête avant le paiement et la fabrication réels. La prochaine étape intégrera stockage sécurisé, analyse IA réelle, génération image/3D, commande et livraison.','Research identity':'Identité de recherche','Edition':'Édition','Researcher Edition · XX':'Édition Chercheur · XX','Create another':'En créer un autre','Back to website':'Retour au site',
    'Your university or lab':'Votre université ou laboratoire','e.g. AI & Robotics':'ex. IA & Robotique','Using your research identity...':'Utilisation de votre identité de recherche…','Creating a starter profile from role and field.':'Création d’un profil initial à partir de votre fonction et de votre domaine.','Building a research word cloud...':'Création du nuage de mots…','Finding recurring themes and research concepts.':'Repérage des thèmes et concepts récurrents.','Connecting signals across papers, code and profiles.':'Mise en relation des signaux issus des articles, du code et des profils.','Connecting methods and systems...':'Connexion des méthodes et systèmes…','Linking methods to projects and research systems.':'Association des méthodes aux projets et systèmes de recherche.','Ranking traceable objects...':'Classement des objets traçables…','Preparing ten candidates by relevance and visual meaning.':'Préparation de dix candidats selon leur pertinence et leur force visuelle.','Preparing ten candidates with evidence trails.':'Préparation de dix candidats avec leurs traces de preuve.','Building your Researcher DNA...':'Création de votre Researcher DNA…','Preparing a profile you can review and edit.':'Préparation d’un profil que vous pouvez vérifier et modifier.','Please select 3–5 signature objects.':'Sélectionnez 3 à 5 objets signature.','You can select up to 5 objects.':'Vous pouvez sélectionner jusqu’à 5 objets.','Select at least 3':'Sélectionnez-en au moins 3','View trace':'Voir la trace','Traceable evidence':'Preuve traçable',
    'AI Systems Researcher':'Chercheur en systèmes IA','Life Science Researcher':'Chercheur en sciences du vivant','Researcher':'Chercheur','Foundation Models · Multimodal AI · Intelligent Systems':'Modèles fondamentaux · IA multimodale · Systèmes intelligents','Transformers · Representation Learning · Deep Learning':'Transformers · Apprentissage de représentations · Deep Learning','Large Language Model · AI Agent · Compute':'Grand modèle de langage · Agent IA · Calcul','Foundation-model research system':'Système de recherche sur les modèles fondamentaux','Robotics · Intelligent Systems · Digital Twins':'Robotique · Systèmes intelligents · Jumeaux numériques','Transformers · Representation Learning · Control':'Transformers · Apprentissage de représentations · Contrôle','Robot · Large Language Model · Digital Twin':'Robot · Grand modèle de langage · Jumeau numérique','Molecular Systems · Computational Biology':'Systèmes moléculaires · Biologie computationnelle','Experimental Analysis · Modeling · Machine Learning':'Analyse expérimentale · Modélisation · Machine Learning','Protein · DNA · Imaging System':'Protéine · ADN · Système d’imagerie','Computational life-science system':'Système computationnel pour les sciences du vivant','Research Questions · Systems · Contributions':'Questions de recherche · Systèmes · Contributions','Analysis · Experimentation · Modeling':'Analyse · Expérimentation · Modélisation','Research Instrument · Data · Model':'Instrument de recherche · Données · Modèle','Research project':'Projet de recherche',
    'Robot Arm':'Bras robotique','Vision System':'Système de vision','Sensor Network':'Réseau de capteurs','Dataset':'Jeu de données','Research Paper':'Article scientifique','Neural Network':'Réseau neuronal','Simulation World':'Environnement de simulation','Protein Structure':'Structure protéique','DNA':'ADN','Microscope':'Microscope','Cell Model':'Modèle cellulaire','Genome':'Génome','Imaging System':'Système d’imagerie','AI Agent':'Agent IA','GitHub Repository':'Dépôt GitHub','Controller':'Contrôleur','Research Instrument':'Instrument de recherche','Experiment':'Expérience','Lab Notebook':'Cahier de laboratoire','Telescope':'Télescope','Satellite':'Satellite',
    'Verified · papers + projects':'Vérifié · articles + projets','Verified · papers + GitHub':'Vérifié · articles + GitHub','Verified · projects + CV':'Vérifié · projets + CV','Inferred · papers + code':'Inféré · articles + code','Verified · project evidence':'Vérifié · preuves de projet','Inferred · GitHub workflow':'Inféré · workflow GitHub','Verified · papers + repositories':'Vérifié · articles + dépôts','Verified · publication record':'Vérifié · publications','Inferred · methods across sources':'Inféré · méthodes dans plusieurs sources','Verified · projects + code':'Vérifié · projets + code','Verified · papers + figures':'Vérifié · articles + figures','Verified · research topics':'Vérifié · thèmes de recherche','Verified · methods + projects':'Vérifié · méthodes + projets','Verified · papers':'Vérifié · articles','Verified · publication evidence':'Vérifié · publications','Verified · methods':'Vérifié · méthodes','Verified · data sources':'Vérifié · sources de données','Inferred · computational methods':'Inféré · méthodes computationnelles','Inferred · research workflow':'Inféré · workflow de recherche','Verified · papers + code':'Vérifié · articles + code','Verified · methods across sources':'Vérifié · méthodes multi-sources','Verified · repository evidence':'Vérifié · dépôt','Inferred · multimodal research':'Inféré · recherche multimodale','Inferred · linked projects':'Inféré · projets liés','Inferred · embodied-AI direction':'Inféré · IA incarnée','Verified · research sources':'Vérifié · sources de recherche','Inferred · modeling evidence':'Inféré · preuves de modélisation','Inferred · project evidence':'Inféré · preuves de projet','Inferred · system-level theme':'Inféré · thème système'
  };

  const dictionaries={zh,fr};
  let currentLang=new URLSearchParams(location.search).get('lang')||localStorage.getItem('researcherdna-lang')||'en';
  if(!['en','zh','fr'].includes(currentLang))currentLang='en';

  const textNodes=[];
  const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT,{acceptNode(node){
    if(!node.parentElement||['SCRIPT','STYLE','NOSCRIPT'].includes(node.parentElement.tagName)||node.parentElement.closest('[data-no-translate]'))return NodeFilter.FILTER_REJECT;
    return node.nodeValue.trim()?NodeFilter.FILTER_ACCEPT:NodeFilter.FILTER_REJECT;
  }});
  while(walker.nextNode()){const node=walker.currentNode;textNodes.push({node,base:node.nodeValue});}
  const attrRecords=[];
  document.querySelectorAll('[placeholder],[aria-label],[title]').forEach(el=>['placeholder','aria-label','title'].forEach(attr=>{if(el.hasAttribute(attr))attrRecords.push({el,attr,base:el.getAttribute(attr)});}));

  function translateText(base,lang=currentLang){if(lang==='en')return base;return dictionaries[lang]?.[base]||base;}
  function applyLocale(lang,updateUrl=true){
    currentLang=['en','zh','fr'].includes(lang)?lang:'en';
    document.documentElement.lang=currentLang==='zh'?'zh-CN':currentLang;
    document.title=translateText('ResearcherDNA — Your Research Matters. Make It Tangible.',currentLang);
    textNodes.forEach(({node,base})=>{const trimmed=base.trim();const translated=translateText(trimmed,currentLang);const start=base.indexOf(trimmed);node.nodeValue=start>=0?base.slice(0,start)+translated+base.slice(start+trimmed.length):translated;});
    attrRecords.forEach(({el,attr,base})=>el.setAttribute(attr,translateText(base,currentLang)));
    document.querySelectorAll('[data-lang]').forEach(btn=>btn.classList.toggle('active',btn.dataset.lang===currentLang));
    localStorage.setItem('researcherdna-lang',currentLang);
    if(updateUrl){const url=new URL(location.href);if(currentLang==='en')url.searchParams.delete('lang');else url.searchParams.set('lang',currentLang);history.replaceState(null,'',url.pathname+url.search+url.hash);}
    window.dispatchEvent(new CustomEvent('researcherdna:language',{detail:{lang:currentLang}}));
  }
  window.tr=(base)=>translateText(base,currentLang);
  window.getResearcherDNALang=()=>currentLang;
  window.applyResearcherDNALocale=applyLocale;
  document.querySelectorAll('[data-lang]').forEach(btn=>btn.addEventListener('click',()=>applyLocale(btn.dataset.lang)));
  applyLocale(currentLang,false);
})();
