(() => {
  const zh = {
    'ResearchDNA — Turn Your Research Into a Collectible': 'ResearchDNA — 把你的科研做成收藏品',
    'How it works': '如何运作', 'Industrial AI': '工业 AI', 'Predictive Maintenance · Remaining Useful Life': '预测性维护 · 剩余寿命', 'AI · Systems': 'AI · 系统', 'Robotics · PHM': '机器人 · PHM', 'Vision · Learning': '视觉 · 学习', 'YOUR': '你的', 'RESEARCH': '科研', 'INPUT': '输入', 'Example': '示例', 'Examples': '示例', 'For Labs': '实验室方案', 'About': '关于', 'Create yours': '创建你的收藏品',
    'AI-made researcher collectibles': 'AI 驱动的研究者专属收藏品', 'Turn your research': '把你的科研', 'into a collectible.': '做成一件收藏品。',
    'Your papers, code, projects and milestones tell a story. ResearchDNA turns that story into a physical object designed around who you are as a researcher.': '你的论文、代码、项目和科研里程碑共同讲述了你的故事。ResearchDNA 用 AI 理解这段经历，并把它转化为专属于你的实体科研收藏品。',
    'Create my researcher': '创建我的研究者形象', 'See an example': '查看示例', 'Private by default': '默认私密', 'You approve every detail': '每个细节由你确认', 'No design skills needed': '无需设计经验',
    'RESEARCHER SERIES · 001': '研究者系列 · 001', 'INDUSTRIAL AI RESEARCHER': '工业 AI 研究者', 'Bearing': '轴承', 'Robot': '机器人', 'AI Token': 'AI Token', 'Paper': '论文', 'FIELD': '领域', 'FOCUS': '方向', 'Predictive Maintenance': '预测性维护',
    'Signature objects': '标志性科研物件', 'selected from your work': '从你的科研经历中提取', 'Research artifact': '代表性科研作品', 'your flagship work, made physical': '把代表作变成实体',
    'Your research is more than a CV.': '你的科研远不止一份简历。', 'Years of work usually end up as PDFs, GitHub repositories and a few lines on a profile. We turn that invisible journey into something you can': '多年的科研工作往往最终散落在 PDF、GitHub 仓库和个人主页的几行文字里。我们把这段看不见的旅程变成一件你可以', 'see, hold and keep.': '看见、拿在手里并长期保存的作品。',
    'From research to Research DNA.': '从科研经历到 Research DNA。', 'Share your work': '分享你的科研资料', 'Add the sources that represent you: CV, papers, GitHub, Scholar, ORCID or your personal website.': '添加能够代表你的资料：简历、论文、GitHub、Google Scholar、ORCID 或个人主页。',
    'AI builds your Research DNA': 'AI 构建你的 Research DNA', 'We map your fields, methods, research objects, key projects and milestones into a structured identity.': '我们把研究领域、方法、研究对象、关键项目和里程碑整理成结构化的科研身份。',
    'Choose what represents you': '选择真正代表你的元素', 'AI proposes the 3–5 objects that best tell your research story. You keep, replace or edit them.': 'AI 提出最能讲述你科研故事的 3–5 个元素，你可以保留、替换或编辑。',
    'We make it physical': '把它做成实体', 'You approve the final concept. We turn it into a collectible figure, research artifact, DNA card and NFC profile.': '你确认最终方案后，我们把它制作成研究者玩偶、科研作品、DNA 收藏卡和 NFC 数字档案。',
    'One researcher. One visual identity.': '一个研究者，一套独特的视觉身份。', 'Education · Projects · Skills': '教育 · 项目 · 技能', '24 publications': '24 篇论文', 'PHM · Robotics · Digital Twin': 'PHM · 机器人 · 数字孪生', 'GitHub repositories': 'GitHub 仓库', 'PyTorch · RUL · Research code': 'PyTorch · RUL · 科研代码', 'Research profile': '科研档案', 'Timeline · affiliations · projects': '时间线 · 机构 · 项目', 'identity': '身份', 'extraction': '提取',
    'RESEARCH DNA': 'RESEARCH DNA', 'Industrial AI Researcher': '工业 AI 研究者', 'research identity · verified': '科研身份 · 已验证', 'Primary field': '主要领域', 'Research focus': '研究方向', 'Predictive Maintenance · RUL': '预测性维护 · RUL', 'Methods': '方法', 'Transformer · Representation Learning': 'Transformer · 表征学习', 'Objects': '研究对象', 'Bearing · Robot · Battery': '轴承 · 机器人 · 电池', 'Flagship work': '代表作',
    'Five objects that tell the story': '五个物件讲述你的科研故事', 'Every object earns its place.': '每个物件都有被选中的理由。', 'ResearchDNA does not simply count keywords. It balances research relevance, recurrence, uniqueness and visual meaning to suggest the objects that best represent the person.': 'ResearchDNA 不只是统计关键词，而是综合科研相关性、出现频率、独特性和视觉表达价值，挑选最能代表这个研究者的物件。', 'Build my Research DNA': '构建我的 Research DNA',
    'Core physical system across degradation and RUL research.': '贯穿退化建模与 RUL 研究的核心物理对象。', 'VERIFIED · 8 SOURCES': '已验证 · 8 个来源', 'Robot Arm': '机械臂', 'Represents robotic motion planning and digital-twin work.': '代表机器人运动规划与数字孪生相关工作。', 'VERIFIED · 3 SOURCES': '已验证 · 3 个来源', 'A visual abstraction of reusable degradation representations.': '对可复用退化表征的视觉化抽象。', 'INFERRED · AI SUGGESTED': 'AI 推断 · 建议',
    'The output': '最终输出', 'More than a figurine.': '不只是一个玩偶。', 'PHYSICAL': '实体', 'Researcher Figure + Signature Objects': '研究者玩偶 + 标志性科研物件', 'A stylized 15 cm figure with 3–5 research objects selected from your Research DNA.': '一个约 15 cm 的风格化人物，加上从 Research DNA 中选出的 3–5 个科研物件。', 'Flagship Research Artifact': '代表性科研作品', 'A small object or scene inspired by your most representative work.': '从你最有代表性的工作中提炼出来的小型实体或场景。', 'Research DNA Card': 'Research DNA 收藏卡', 'Your field, methods, projects and milestones summarized as a collectible identity card.': '把你的领域、方法、项目和里程碑浓缩成一张可收藏的科研身份卡。', 'DIGITAL': '数字', 'NFC Research Profile': 'NFC 科研档案', 'Tap the base to open a private or public research profile with papers, code, timeline and AI Q&A.': '轻触底座即可打开私密或公开的数字科研档案，展示论文、代码、时间线和 AI 问答。',
    'For research groups': '面向科研团队', 'Turn your lab': '把你的实验室', 'into a collection.': '做成一整套收藏系列。', "Create one visual system for the whole team while preserving each member's individual Research DNA. Designed for graduations, anniversaries, farewells and conference gifts.": '为整个团队建立统一的视觉体系，同时保留每位成员独有的 Research DNA，适用于毕业、周年、离组纪念和会议礼物。', 'Create a lab collection': '创建实验室系列', 'Professor': '教授', 'Researcher 01': '研究者 01', 'Researcher 02': '研究者 02',
    'Built for researchers': '为研究者而设计', 'AI proposes. You decide.': 'AI 提议，你来决定。', 'Evidence first': '证据优先', 'Every major Research DNA item can point back to the paper, repository or profile that supports it.': 'Research DNA 中的重要结论都可以追溯到支持它的论文、代码仓库或个人资料。', 'Your uploads and profile stay private unless you choose to publish them. Unpublished work is never exposed.': '除非你主动选择公开，否则上传内容和个人档案保持私密；未发表工作不会被公开。', 'Human approval': '人工确认', 'Nothing goes into production until you approve the identity, objects, packaging and final design.': '在你确认科研身份、物件、包装和最终设计之前，不会进入生产。',
    'Choose an edition': '选择版本', 'Start digital. Make it physical.': '先从数字体验开始，再把它变成实体。', 'Research DNA': 'Research DNA', 'Identity profile and digital collectible artwork.': '科研身份档案与数字收藏品视觉稿。', 'Digital profile': '数字科研档案', 'Collectible artwork': '收藏品视觉稿', 'Start digital': '从数字版开始', 'RESEARCHER EDITION': '研究者版', 'The Collectible': '实体收藏版', 'The complete researcher figure and signature object set.': '完整的研究者玩偶与标志性科研物件组合。', '15 cm researcher figure': '15 cm 研究者玩偶', '5 signature research objects': '5 个标志性科研物件', 'Research DNA card': 'Research DNA 收藏卡', 'Collector packaging': '收藏级包装', 'Create mine': '创建我的版本', 'ARTIFACT EDITION': '科研作品版', 'Flagship Edition': '旗舰版', 'For the research milestone you want to keep.': '为值得永久保存的科研里程碑而设计。', 'Everything in Researcher Edition': '包含研究者版全部内容', 'Flagship research artifact': '代表性科研作品', 'NFC display base': 'NFC 展示底座', 'Numbered collector card': '编号收藏卡', 'Create flagship': '创建旗舰版', 'Prototype pricing for concept validation. Manufacturing and shipping are not connected in this demo.': '当前价格仅用于概念验证；此演示尚未连接真实制造和物流。',
    'Your work deserves more than a line on a CV.': '你的科研值得的不只是一行简历。', 'You spent years building your research.': '你花了多年构建自己的科研。', 'Now turn it into something you can hold.': '现在，把它变成一件真正能拿在手里的作品。', 'Create your researcher': '创建你的研究者收藏品', 'Research identity, made physical.': '把科研身份变成实体。', 'Privacy': '隐私', '© 2026 ResearchDNA. Concept prototype.': '© 2026 ResearchDNA · 概念原型',
    'Identity': '身份', 'Research': '科研资料', 'Preview': '预览', 'STEP 1 · IDENTITY': '第 1 步 · 身份', 'Who are we creating?': '我们要为谁创建？', 'Tell us the basics. You can edit everything later.': '先告诉我们基本信息，之后都可以修改。', 'First name': '名', 'Last name': '姓', 'Current role': '当前身份', 'PhD Researcher': '博士研究人员', 'Postdoctoral Researcher': '博士后研究人员', 'Research Scientist': '研究科学家', 'Research Engineer': '研究工程师', 'Other': '其他', 'Institution': '机构', 'Primary research field': '主要研究领域', 'What is this for?': '这次创建用于什么场景？', 'For myself': '为自己', 'PhD graduation': '博士毕业', 'Researcher gift': '研究者礼物', 'Lab member': '实验室成员', 'Continue': '继续',
    'STEP 2 · RESEARCH': '第 2 步 · 科研资料', 'Share the work that represents you.': '分享能够代表你的科研资料。', 'Research sources are optional for your first preview. You can continue without uploading anything and add verified sources later.': '第一次预览不需要上传任何资料。你可以先根据身份和研究领域生成初始 Research DNA，之后再添加论文和代码进行验证。', 'Drop CV or papers here': '把简历或论文拖到这里', 'PDF, DOCX · Demo only': 'PDF、DOCX · 当前仅本地演示', 'Choose files': '选择文件', 'Google Scholar': 'Google Scholar', 'ORCID / Personal website': 'ORCID / 个人主页', 'Continue without uploading': '不上传，直接体验', 'Build a starter Research DNA from your role and research field.': '根据你的身份和研究领域生成初始 Research DNA。', 'Load demo research sources': '加载演示科研资料', 'Fastest way to preview the experience.': '最快体验完整流程。', 'Private by default': '默认私密', 'In a production version, users would control retention, deletion and profile visibility before analysis.': '正式版本中，用户可在分析前控制资料保留、删除和档案可见性。', 'Back': '返回', 'Analyze my research': '分析我的科研',
    'BUILDING YOUR RESEARCH DNA': '正在构建你的 RESEARCH DNA', 'Reading publications...': '正在读取论文…', 'Extracting research topics, methods and recurring objects.': '正在提取研究主题、方法和反复出现的研究对象。', 'STEP 3 · RESEARCH DNA': '第 3 步 · RESEARCH DNA', 'Your research, distilled.': '把你的科研浓缩成身份。', 'AI proposes. You decide what belongs in the final identity.': 'AI 给出建议，最终由你决定哪些内容属于你的科研身份。', 'RESEARCH IDENTITY': '科研身份', 'grounded in provided sources': '基于已提供资料', 'starter profile · not source-verified': '初始画像 · 尚未经过资料验证', 'Research objects': '研究对象', 'publications': '论文', 'research themes': '研究主题', 'methods': '方法', 'candidate objects': '候选物件', 'SIGNATURE OBJECTS': '标志性科研物件', 'Five objects we think represent your research.': '我们认为最能代表你的五个物件。', 'Click an object to replace it.': '点击物件即可替换。', 'Verified · 8 sources': '已验证 · 8 个来源', 'Replace': '替换', 'Verified · 3 sources': '已验证 · 3 个来源', 'Inferred · AI suggested': 'AI 推断 · 建议', 'Laptop': '笔记本电脑', 'Suggested · workflow': '建议 · 工作流', 'Research Paper': '研究论文', 'Verified · 24 sources': '已验证 · 24 个来源', 'User selected · editable': '用户选择 · 可编辑', 'Continue to design': '继续设计',
    'STEP 4 · PREVIEW': '第 4 步 · 预览', 'Meet your researcher.': '看看你的研究者收藏品。', 'A concept preview based on your Research DNA. Production would require a final 3D design approval.': '这是基于 Research DNA 生成的概念预览；真实生产前还会进行最终 3D 设计确认。', 'PHD RESEARCHER · INDUSTRIAL AI': '博士研究人员 · 工业 AI', 'FLAGSHIP': '代表作', 'NFC PROFILE': 'NFC 档案', 'Tap to explore ↗': '轻触查看 ↗', "WHAT'S INCLUDED": '包含内容', 'Researcher Edition': '研究者版', 'prototype': '原型', 'Digital research profile': '数字科研档案', 'You approve before production': '生产前由你确认', 'Nothing would be manufactured until the final design is approved.': '最终设计获得确认前不会进入制造。', 'Continue to order': '继续下单', 'Edit Research DNA': '编辑 Research DNA',
    'PROTOTYPE COMPLETE': '原型体验完成', 'Your concept is ready.': '你的概念方案已经生成。', 'This prototype currently stops before real payment and manufacturing. The next production layer will connect authentication, file storage, AI analysis, image/3D generation, Stripe and order tracking.': '当前原型暂时停在真实付款和制造之前。下一阶段将连接账号系统、文件存储、AI 分析、图像/3D 生成、Stripe 支付和订单追踪。', 'Research identity': '科研身份', 'Edition': '版本', 'Researcher Edition · €149': '研究者版 · €149', 'Create another': '再创建一个', 'Back to website': '返回网站', 'REPLACE OBJECT': '替换物件', 'Choose another signal.': '选择另一个代表元素。', 'Battery': '电池', 'GPU': 'GPU', 'Machine Tool': '机床', 'Digital Twin': '数字孪生', 'Python': 'Python', 'Sensor': '传感器',
    'Using your research identity...': '正在使用你的科研身份…', 'Creating a starter profile from role and field.': '正在根据身份和研究领域创建初始画像。', 'Mapping research themes...': '正在梳理研究主题…', 'Grouping recurring topics and research problems.': '正在整理高频主题和研究问题。', 'Connecting methods and objects...': '正在连接方法与研究对象…', 'Linking methods to physical systems and projects.': '正在把方法与物理系统和项目关联起来。', 'Ranking signature elements...': '正在筛选标志性元素…', 'Scoring relevance, uniqueness and visual meaning.': '正在评估相关性、独特性和视觉表达价值。', 'Building your Research DNA...': '正在生成你的 Research DNA…', 'Preparing a profile you can review and edit.': '正在准备可供你确认和编辑的科研画像。',
    'AI Systems': 'AI 系统', 'Machine Learning · Representation Learning': '机器学习 · 表征学习', 'Transformer · Deep Learning': 'Transformer · 深度学习', 'Model · Data · Compute': '模型 · 数据 · 算力', 'Starter Concept': '初始概念', 'Robotics Researcher': '机器人研究者', 'Robotics · Motion Planning': '机器人 · 运动规划', 'Control · Learning': '控制 · 学习', 'Robot Arm · Sensor · Controller': '机械臂 · 传感器 · 控制器', 'Robot System': '机器人系统', 'Life Science Researcher': '生命科学研究者', 'Molecular & Cellular Research': '分子与细胞研究', 'Experimental Analysis · Modeling': '实验分析 · 建模', 'Protein · DNA · Microscope': '蛋白质 · DNA · 显微镜', 'Molecular System': '分子系统', 'Researcher': '研究者', 'Research Problems · Methods': '研究问题 · 方法', 'Analysis · Experimentation': '分析 · 实验', 'Data · Model · Paper': '数据 · 模型 · 论文', 'Research Project': '科研项目'
  };

  const fr = {
    'ResearchDNA — Turn Your Research Into a Collectible': 'ResearchDNA — Transformez votre recherche en objet de collection',
    'How it works': 'Comment ça marche', 'Industrial AI': 'IA industrielle', 'Predictive Maintenance · Remaining Useful Life': 'Maintenance prédictive · Durée de vie restante', 'AI · Systems': 'IA · Systèmes', 'Robotics · PHM': 'Robotique · PHM', 'Vision · Learning': 'Vision · Apprentissage', 'YOUR': 'VOTRE', 'RESEARCH': 'RECHERCHE', 'INPUT': 'ENTRÉE', 'Example': 'Exemple', 'Examples': 'Exemples', 'For Labs': 'Pour les labos', 'About': 'À propos', 'Create yours': 'Créer le vôtre',
    'AI-made researcher collectibles': 'Objets de collection pour chercheurs, conçus par IA', 'Turn your research': 'Transformez votre recherche', 'into a collectible.': 'en objet de collection.',
    'Your papers, code, projects and milestones tell a story. ResearchDNA turns that story into a physical object designed around who you are as a researcher.': 'Vos articles, votre code, vos projets et vos étapes clés racontent une histoire. ResearchDNA comprend ce parcours et le transforme en un objet physique conçu autour de votre identité de chercheur.',
    'Create my researcher': 'Créer mon chercheur', 'See an example': 'Voir un exemple', 'Private by default': 'Privé par défaut', 'You approve every detail': 'Vous validez chaque détail', 'No design skills needed': 'Aucune compétence en design requise',
    'RESEARCHER SERIES · 001': 'SÉRIE CHERCHEURS · 001', 'INDUSTRIAL AI RESEARCHER': 'CHERCHEUR EN IA INDUSTRIELLE', 'Bearing': 'Roulement', 'Robot': 'Robot', 'AI Token': 'Token IA', 'Paper': 'Article', 'FIELD': 'DOMAINE', 'FOCUS': 'AXE', 'Predictive Maintenance': 'Maintenance prédictive',
    'Signature objects': 'Objets signature', 'selected from your work': 'sélectionnés à partir de vos travaux', 'Research artifact': 'Artefact de recherche', 'your flagship work, made physical': 'votre travail phare rendu physique',
    'Your research is more than a CV.': 'Votre recherche ne se résume pas à un CV.', 'Years of work usually end up as PDFs, GitHub repositories and a few lines on a profile. We turn that invisible journey into something you can': 'Des années de travail finissent souvent dispersées entre PDF, dépôts GitHub et quelques lignes sur un profil. Nous transformons ce parcours invisible en quelque chose que vous pouvez', 'see, hold and keep.': 'voir, toucher et conserver.',
    'From research to Research DNA.': 'De la recherche au Research DNA.', 'Share your work': 'Partagez vos travaux', 'Add the sources that represent you: CV, papers, GitHub, Scholar, ORCID or your personal website.': 'Ajoutez les sources qui vous représentent : CV, articles, GitHub, Google Scholar, ORCID ou site personnel.',
    'AI builds your Research DNA': 'L’IA construit votre Research DNA', 'We map your fields, methods, research objects, key projects and milestones into a structured identity.': 'Nous structurons vos domaines, méthodes, objets de recherche, projets clés et étapes de carrière en une identité de recherche.',
    'Choose what represents you': 'Choisissez ce qui vous représente', 'AI proposes the 3–5 objects that best tell your research story. You keep, replace or edit them.': 'L’IA propose 3 à 5 objets qui racontent le mieux votre parcours. Vous pouvez les conserver, les remplacer ou les modifier.',
    'We make it physical': 'Nous le rendons physique', 'You approve the final concept. We turn it into a collectible figure, research artifact, DNA card and NFC profile.': 'Vous validez le concept final, puis nous le transformons en figurine, artefact de recherche, carte DNA et profil NFC.',
    'One researcher. One visual identity.': 'Un chercheur. Une identité visuelle.', 'Education · Projects · Skills': 'Formation · Projets · Compétences', '24 publications': '24 publications', 'PHM · Robotics · Digital Twin': 'PHM · Robotique · Jumeau numérique', 'GitHub repositories': 'Dépôts GitHub', 'PyTorch · RUL · Research code': 'PyTorch · RUL · Code de recherche', 'Research profile': 'Profil de recherche', 'Timeline · affiliations · projects': 'Parcours · affiliations · projets', 'identity': 'identité', 'extraction': 'extraction',
    'Industrial AI Researcher': 'Chercheur en IA industrielle', 'research identity · verified': 'identité de recherche · vérifiée', 'Primary field': 'Domaine principal', 'Research focus': 'Axes de recherche', 'Predictive Maintenance · RUL': 'Maintenance prédictive · RUL', 'Methods': 'Méthodes', 'Transformer · Representation Learning': 'Transformer · Apprentissage de représentations', 'Objects': 'Objets', 'Bearing · Robot · Battery': 'Roulement · Robot · Batterie', 'Flagship work': 'Travail phare',
    'Five objects that tell the story': 'Cinq objets pour raconter le parcours', 'Every object earns its place.': 'Chaque objet a une raison d’être là.', 'ResearchDNA does not simply count keywords. It balances research relevance, recurrence, uniqueness and visual meaning to suggest the objects that best represent the person.': 'ResearchDNA ne se contente pas de compter les mots-clés. Il combine pertinence scientifique, récurrence, singularité et potentiel visuel pour proposer les objets qui représentent le mieux la personne.', 'Build my Research DNA': 'Construire mon Research DNA',
    'Core physical system across degradation and RUL research.': 'Système physique central dans les travaux sur la dégradation et la RUL.', 'VERIFIED · 8 SOURCES': 'VÉRIFIÉ · 8 SOURCES', 'Robot Arm': 'Bras robotique', 'Represents robotic motion planning and digital-twin work.': 'Représente les travaux en planification robotique et jumeau numérique.', 'VERIFIED · 3 SOURCES': 'VÉRIFIÉ · 3 SOURCES', 'A visual abstraction of reusable degradation representations.': 'Une abstraction visuelle des représentations réutilisables de la dégradation.', 'INFERRED · AI SUGGESTED': 'INFÉRÉ · SUGGÉRÉ PAR IA',
    'The output': 'Le résultat', 'More than a figurine.': 'Bien plus qu’une figurine.', 'PHYSICAL': 'PHYSIQUE', 'Researcher Figure + Signature Objects': 'Figurine du chercheur + objets signature', 'A stylized 15 cm figure with 3–5 research objects selected from your Research DNA.': 'Une figurine stylisée d’environ 15 cm avec 3 à 5 objets de recherche issus de votre Research DNA.', 'Flagship Research Artifact': 'Artefact de recherche phare', 'A small object or scene inspired by your most representative work.': 'Un petit objet ou une scène inspirée de votre travail le plus représentatif.', 'Research DNA Card': 'Carte Research DNA', 'Your field, methods, projects and milestones summarized as a collectible identity card.': 'Votre domaine, vos méthodes, projets et étapes clés résumés dans une carte d’identité de collection.', 'DIGITAL': 'NUMÉRIQUE', 'NFC Research Profile': 'Profil de recherche NFC', 'Tap the base to open a private or public research profile with papers, code, timeline and AI Q&A.': 'Touchez la base pour ouvrir un profil de recherche privé ou public avec articles, code, parcours et questions-réponses IA.',
    'For research groups': 'Pour les équipes de recherche', 'Turn your lab': 'Transformez votre labo', 'into a collection.': 'en collection.', "Create one visual system for the whole team while preserving each member's individual Research DNA. Designed for graduations, anniversaries, farewells and conference gifts.": 'Créez un système visuel commun à toute l’équipe tout en conservant le Research DNA individuel de chaque membre. Idéal pour soutenances, anniversaires, départs et cadeaux de conférence.', 'Create a lab collection': 'Créer une collection de labo', 'Professor': 'Professeur', 'Researcher 01': 'Chercheur 01', 'Researcher 02': 'Chercheur 02',
    'Built for researchers': 'Pensé pour les chercheurs', 'AI proposes. You decide.': 'L’IA propose. Vous décidez.', 'Evidence first': 'Des preuves avant tout', 'Every major Research DNA item can point back to the paper, repository or profile that supports it.': 'Chaque élément majeur du Research DNA peut renvoyer vers l’article, le dépôt ou le profil qui le justifie.', 'Your uploads and profile stay private unless you choose to publish them. Unpublished work is never exposed.': 'Vos fichiers et votre profil restent privés sauf si vous choisissez de les publier. Les travaux non publiés ne sont jamais exposés.', 'Human approval': 'Validation humaine', 'Nothing goes into production until you approve the identity, objects, packaging and final design.': 'Rien ne part en production avant votre validation de l’identité, des objets, du packaging et du design final.',
    'Choose an edition': 'Choisissez une édition', 'Start digital. Make it physical.': 'Commencez en numérique. Rendez-le physique.', 'Identity profile and digital collectible artwork.': 'Profil d’identité de recherche et visuel numérique de collection.', 'Digital profile': 'Profil numérique', 'Collectible artwork': 'Visuel de collection', 'Start digital': 'Commencer en numérique', 'RESEARCHER EDITION': 'ÉDITION CHERCHEUR', 'The Collectible': 'La collection', 'The complete researcher figure and signature object set.': 'La figurine complète du chercheur et son ensemble d’objets signature.', '15 cm researcher figure': 'Figurine chercheur de 15 cm', '5 signature research objects': '5 objets de recherche signature', 'Research DNA card': 'Carte Research DNA', 'Collector packaging': 'Packaging de collection', 'Create mine': 'Créer le mien', 'ARTIFACT EDITION': 'ÉDITION ARTEFACT', 'Flagship Edition': 'Édition phare', 'For the research milestone you want to keep.': 'Pour le jalon scientifique que vous souhaitez conserver.', 'Everything in Researcher Edition': 'Tout le contenu de l’Édition Chercheur', 'Flagship research artifact': 'Artefact de recherche phare', 'NFC display base': 'Socle NFC', 'Numbered collector card': 'Carte de collection numérotée', 'Create flagship': 'Créer l’édition phare', 'Prototype pricing for concept validation. Manufacturing and shipping are not connected in this demo.': 'Tarifs de prototype pour valider le concept. La fabrication et l’expédition ne sont pas encore connectées dans cette démo.',
    'Your work deserves more than a line on a CV.': 'Votre travail mérite plus qu’une ligne sur un CV.', 'You spent years building your research.': 'Vous avez passé des années à construire votre recherche.', 'Now turn it into something you can hold.': 'Transformez-la maintenant en un objet que vous pouvez tenir en main.', 'Create your researcher': 'Créer votre chercheur', 'Research identity, made physical.': 'L’identité de recherche, rendue physique.', 'Privacy': 'Confidentialité', '© 2026 ResearchDNA. Concept prototype.': '© 2026 ResearchDNA · Prototype conceptuel',
    'Identity': 'Identité', 'Research': 'Recherche', 'Preview': 'Aperçu', 'STEP 1 · IDENTITY': 'ÉTAPE 1 · IDENTITÉ', 'Who are we creating?': 'Pour qui créons-nous cet objet ?', 'Tell us the basics. You can edit everything later.': 'Donnez-nous les informations essentielles. Vous pourrez tout modifier ensuite.', 'First name': 'Prénom', 'Last name': 'Nom', 'Current role': 'Fonction actuelle', 'PhD Researcher': 'Doctorant / Chercheur PhD', 'Postdoctoral Researcher': 'Chercheur postdoctoral', 'Research Scientist': 'Chercheur scientifique', 'Research Engineer': 'Ingénieur de recherche', 'Other': 'Autre', 'Institution': 'Établissement', 'Primary research field': 'Domaine de recherche principal', 'What is this for?': 'Pour quelle occasion ?', 'For myself': 'Pour moi', 'PhD graduation': 'Fin de doctorat', 'Researcher gift': 'Cadeau pour chercheur', 'Lab member': 'Membre du labo', 'Continue': 'Continuer',
    'STEP 2 · RESEARCH': 'ÉTAPE 2 · RECHERCHE', 'Share the work that represents you.': 'Partagez les travaux qui vous représentent.', 'Research sources are optional for your first preview. You can continue without uploading anything and add verified sources later.': 'Les sources sont facultatives pour le premier aperçu. Vous pouvez continuer sans rien téléverser puis ajouter des sources vérifiées plus tard.', 'Drop CV or papers here': 'Déposez votre CV ou vos articles ici', 'PDF, DOCX · Demo only': 'PDF, DOCX · Démo locale', 'Choose files': 'Choisir des fichiers', 'ORCID / Personal website': 'ORCID / Site personnel', 'Continue without uploading': 'Continuer sans téléverser', 'Build a starter Research DNA from your role and research field.': 'Créer un Research DNA initial à partir de votre fonction et de votre domaine.', 'Load demo research sources': 'Charger des sources de démonstration', 'Fastest way to preview the experience.': 'Le moyen le plus rapide de tester toute l’expérience.', 'In a production version, users would control retention, deletion and profile visibility before analysis.': 'Dans la version finale, l’utilisateur contrôlera la conservation, la suppression et la visibilité du profil avant l’analyse.', 'Back': 'Retour', 'Analyze my research': 'Analyser ma recherche',
    'BUILDING YOUR RESEARCH DNA': 'CRÉATION DE VOTRE RESEARCH DNA', 'Reading publications...': 'Lecture des publications…', 'Extracting research topics, methods and recurring objects.': 'Extraction des thèmes, méthodes et objets de recherche récurrents.', 'STEP 3 · RESEARCH DNA': 'ÉTAPE 3 · RESEARCH DNA', 'Your research, distilled.': 'Votre recherche, condensée.', 'AI proposes. You decide what belongs in the final identity.': 'L’IA propose. Vous décidez de ce qui appartient à votre identité finale.', 'RESEARCH IDENTITY': 'IDENTITÉ DE RECHERCHE', 'grounded in provided sources': 'fondé sur les sources fournies', 'starter profile · not source-verified': 'profil initial · non vérifié par des sources', 'Research objects': 'Objets de recherche', 'publications': 'publications', 'research themes': 'thèmes de recherche', 'methods': 'méthodes', 'candidate objects': 'objets candidats', 'SIGNATURE OBJECTS': 'OBJETS SIGNATURE', 'Five objects we think represent your research.': 'Cinq objets qui, selon nous, représentent votre recherche.', 'Click an object to replace it.': 'Cliquez sur un objet pour le remplacer.', 'Verified · 8 sources': 'Vérifié · 8 sources', 'Replace': 'Remplacer', 'Verified · 3 sources': 'Vérifié · 3 sources', 'Inferred · AI suggested': 'Inféré · suggéré par IA', 'Laptop': 'Ordinateur portable', 'Suggested · workflow': 'Suggéré · workflow', 'Research Paper': 'Article scientifique', 'Verified · 24 sources': 'Vérifié · 24 sources', 'User selected · editable': 'Choisi par l’utilisateur · modifiable', 'Continue to design': 'Continuer vers le design',
    'STEP 4 · PREVIEW': 'ÉTAPE 4 · APERÇU', 'Meet your researcher.': 'Découvrez votre chercheur.', 'A concept preview based on your Research DNA. Production would require a final 3D design approval.': 'Un aperçu conceptuel fondé sur votre Research DNA. La production nécessiterait une validation finale du design 3D.', 'PHD RESEARCHER · INDUSTRIAL AI': 'CHERCHEUR PHD · IA INDUSTRIELLE', 'FLAGSHIP': 'TRAVAIL PHARE', 'NFC PROFILE': 'PROFIL NFC', 'Tap to explore ↗': 'Touchez pour explorer ↗', "WHAT'S INCLUDED": 'CONTENU', 'Researcher Edition': 'Édition Chercheur', 'prototype': 'prototype', 'Digital research profile': 'Profil de recherche numérique', 'You approve before production': 'Vous validez avant production', 'Nothing would be manufactured until the final design is approved.': 'Rien ne sera fabriqué avant validation du design final.', 'Continue to order': 'Continuer vers la commande', 'Edit Research DNA': 'Modifier le Research DNA',
    'PROTOTYPE COMPLETE': 'PROTOTYPE TERMINÉ', 'Your concept is ready.': 'Votre concept est prêt.', 'This prototype currently stops before real payment and manufacturing. The next production layer will connect authentication, file storage, AI analysis, image/3D generation, Stripe and order tracking.': 'Ce prototype s’arrête actuellement avant le paiement et la fabrication réels. L’étape suivante connectera l’authentification, le stockage, l’analyse IA, la génération image/3D, Stripe et le suivi de commande.', 'Research identity': 'Identité de recherche', 'Edition': 'Édition', 'Researcher Edition · €149': 'Édition Chercheur · 149 €', 'Create another': 'Créer un autre', 'Back to website': 'Retour au site', 'REPLACE OBJECT': 'REMPLACER L’OBJET', 'Choose another signal.': 'Choisissez un autre élément représentatif.', 'Battery': 'Batterie', 'GPU': 'GPU', 'Machine Tool': 'Machine-outil', 'Digital Twin': 'Jumeau numérique', 'Python': 'Python', 'Sensor': 'Capteur',
    'Using your research identity...': 'Utilisation de votre identité de recherche…', 'Creating a starter profile from role and field.': 'Création d’un profil initial à partir de votre fonction et de votre domaine.', 'Mapping research themes...': 'Cartographie des thèmes de recherche…', 'Grouping recurring topics and research problems.': 'Regroupement des thèmes récurrents et problèmes de recherche.', 'Connecting methods and objects...': 'Connexion des méthodes et objets…', 'Linking methods to physical systems and projects.': 'Association des méthodes aux systèmes physiques et projets.', 'Ranking signature elements...': 'Classement des éléments signature…', 'Scoring relevance, uniqueness and visual meaning.': 'Évaluation de la pertinence, de la singularité et du potentiel visuel.', 'Building your Research DNA...': 'Création de votre Research DNA…', 'Preparing a profile you can review and edit.': 'Préparation d’un profil que vous pourrez vérifier et modifier.',
    'AI Systems': 'Systèmes IA', 'Machine Learning · Representation Learning': 'Machine Learning · Apprentissage de représentations', 'Transformer · Deep Learning': 'Transformer · Deep Learning', 'Model · Data · Compute': 'Modèle · Données · Calcul', 'Starter Concept': 'Concept initial', 'Robotics Researcher': 'Chercheur en robotique', 'Robotics · Motion Planning': 'Robotique · Planification de mouvement', 'Control · Learning': 'Commande · Apprentissage', 'Robot Arm · Sensor · Controller': 'Bras robotique · Capteur · Contrôleur', 'Robot System': 'Système robotique', 'Life Science Researcher': 'Chercheur en sciences du vivant', 'Molecular & Cellular Research': 'Recherche moléculaire et cellulaire', 'Experimental Analysis · Modeling': 'Analyse expérimentale · Modélisation', 'Protein · DNA · Microscope': 'Protéine · ADN · Microscope', 'Molecular System': 'Système moléculaire', 'Researcher': 'Chercheur', 'Research Problems · Methods': 'Problèmes de recherche · Méthodes', 'Analysis · Experimentation': 'Analyse · Expérimentation', 'Data · Model · Paper': 'Données · Modèle · Article', 'Research Project': 'Projet de recherche'
  };

  const dictionaries = { zh, fr };
  let currentLang = new URLSearchParams(location.search).get('lang') || localStorage.getItem('researchdna-lang') || 'en';
  if (!['en','zh','fr'].includes(currentLang)) currentLang = 'en';

  const textNodes = [];
  const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT, {
    acceptNode(node) {
      if (!node.parentElement || ['SCRIPT','STYLE','NOSCRIPT'].includes(node.parentElement.tagName)) return NodeFilter.FILTER_REJECT;
      return node.nodeValue.trim() ? NodeFilter.FILTER_ACCEPT : NodeFilter.FILTER_REJECT;
    }
  });
  while (walker.nextNode()) {
    const node = walker.currentNode;
    textNodes.push({ node, base: node.nodeValue });
  }

  const attrRecords = [];
  document.querySelectorAll('[placeholder],[aria-label],[title]').forEach(el => {
    ['placeholder','aria-label','title'].forEach(attr => {
      if (el.hasAttribute(attr)) attrRecords.push({ el, attr, base: el.getAttribute(attr) });
    });
  });

  function translateText(base, lang=currentLang) {
    if (lang === 'en') return base;
    return dictionaries[lang]?.[base] || base;
  }

  function applyLocale(lang, updateUrl=true) {
    currentLang = ['en','zh','fr'].includes(lang) ? lang : 'en';
    document.documentElement.lang = currentLang === 'zh' ? 'zh-CN' : currentLang;
    document.title = translateText('ResearchDNA — Turn Your Research Into a Collectible', currentLang);
    textNodes.forEach(({node, base}) => {
      const trimmed = base.trim();
      const translated = translateText(trimmed, currentLang);
      const start = base.indexOf(trimmed);
      node.nodeValue = start >= 0 ? base.slice(0,start) + translated + base.slice(start+trimmed.length) : translated;
    });
    attrRecords.forEach(({el,attr,base}) => el.setAttribute(attr, translateText(base,currentLang)));
    document.querySelectorAll('[data-lang]').forEach(btn => btn.classList.toggle('active', btn.dataset.lang === currentLang));
    localStorage.setItem('researchdna-lang', currentLang);
    if (updateUrl) {
      const url = new URL(location.href);
      if (currentLang === 'en') url.searchParams.delete('lang'); else url.searchParams.set('lang', currentLang);
      history.replaceState(null, '', url.pathname + url.search + url.hash);
    }
    window.dispatchEvent(new CustomEvent('researchdna:language', {detail:{lang:currentLang}}));
  }

  window.tr = (base) => translateText(base, currentLang);
  window.getResearchDNALang = () => currentLang;
  window.applyResearchDNALocale = applyLocale;

  document.querySelectorAll('[data-lang]').forEach(btn => btn.addEventListener('click', () => applyLocale(btn.dataset.lang)));
  applyLocale(currentLang, false);
})();
